### ISSUE TITLE
magento 2.3  Class Knawat\Dropshipping\Model\System\Message\ConnectStore does not exist

### ISSUE THREAD

**Issue by volanar** [Knawat/knawat-dropshipping-magento2#35]
In admin configuration error: Class Knawat\Dropshipping\Model\System\Message\ConnectStore does not exist

**Comment by jayjittv** [comment]
Hi @volanar,

Can you please check that you have created folder structure for module like `app/code/Knawat/Dropshipping/` also check your php version is  7.1.3+ or 7.2.x

Also you can use installation guide using below URL for more information
https://github.com/Knawat/knawat-dropshipping-magento2/wiki/1.-Installation-Guide

**Comment by HazemKhaled** [comment]
@volanar please open this issue again if you still face the same issue
