### ISSUE TITLE
Class Knawat\MPFactory does not exist

### ISSUE THREAD

**Issue by MagentoAr** [Knawat/knawat-dropshipping-magento2#43]
Hi
this message appear in Adminpanel after install Knawat in Magento 2.2.7
Class Knawat\MPFactory does not exist

any solutions ?

**Comment by iamdharmesh** [comment]
Hello @MagentoAr,

Thanks for creating issue and sorry for the inconvenience happen to you.

Can you please follow installation steps given here https://github.com/Knawat/knawat-dropshipping-magento2/wiki/1.-Installation-Guide

Maybe you haven't run `composer require knawat/knawat-php-sdk` command. Can you please try after run this command in magneto root directory.

Let us know if you still facing any difficulties.

Thanks,
Dharmesh Patel

**Comment by MagentoAr** [comment]
> Hello @MagentoAr,
> 
> Thanks for creating issue and sorry for the inconvenience happen to you.
> 
> Can you please follow installation steps given here https://github.com/Knawat/knawat-dropshipping-magento2/wiki/1.-Installation-Guide
> 
> Maybe you haven't run `composer require knawat/knawat-php-sdk` command. Can you please try after run this command in magneto root directory.
> 
> Let us know if you still facing any difficulties.
> 
> Thanks,
> Dharmesh Patel

Hi
it's work now
but when i try to import this error appear to me

`Class Knawat\Dropshipping\Helper\ProductImport does not exist`

**Comment by MagentoAr** [comment]
> Hello @MagentoAr ,
> 
> Can you please clone or download latest code from `https://github.com/Knawat/knawat-dropshipping-magento2.git` repository. and replace `app/code/Knawat/Dropshipping` with this downloaded code source, and this will solve your issue.
> 
> Let us know if you still facing any difficulties.
> 
> Thanks,
> Jayjit Gatha

Great it's work now 💯

**Comment by iamdharmesh** [comment]
@MagentoAr  Glad to hear that its working fine now. 

Feel free to create a new issue if you experience any issue or difficulties in future.


Thanks,
Dharmesh Patel
