### ISSUE TITLE
Import products only import one Image for some products !

### ISSUE THREAD

**Issue by MagentoAr** [Knawat/knawat-dropshipping-magento2#47]
Hi all,
when i imports products at the first time it's only import only one image for every product !
but when press import again it's import the other images.
any suggested solutions ?

Thank you

**Comment by jayjittv** [comment]
Hello @MagentoAr ,

Thanks for creating issue.

Please verify products in storefront , images has been displayed properly or not.

In magento every configurable products has  simple associated products that will not be displayed in storefront , it's just for associating size , color etc. options for that configurable products and to reduce upload time we have not uploaded images for associated simple products but every configurable product contains one or more images.

Let us know if you still facing any difficulties.

Thanks,
Jayjit Gatha

**Comment by MagentoAr** [comment]
@jayjittv 
Thank you .. i know that.. but the problem is some products only have one image.. and in the Knawat website it's have more than one.

**Comment by HazemKhaled** [comment]
@MagentoAr can you share an example SKU

**Comment by MagentoAr** [comment]
@HazemKhaled  sorry i have deleted all products and import it again .. and everything works good now.
