### ISSUE TITLE
all of simple products not connected with the Main Configurable products !

### ISSUE THREAD

**Issue by MagentoAr** [Knawat/knawat-dropshipping-magento2#48]
Hi,
theres a lot of configurable products that's not connected right with their simple products.
this issue appear to me after the second import.. all connection between products removed !

**Comment by jayjittv** [comment]
Hi @MagentoAr ,

Thanks for creating issue.

Can you please give me magento version in which you are using this module.

Thanks,
Jayjit Gatha

**Comment by MagentoAr** [comment]
> Hi @MagentoAr ,
> 
> Thanks for creating issue.
> 
> Can you please give me magento version in which you are using this module.
> 
> Thanks,
> Jayjit Gatha

Hi @jayjittv 
i'm using magento 2.2.7

**Comment by jayjittv** [comment]
It's working
