### ISSUE TITLE
Magento 2.1.16 Community Edition compatibility 

### ISSUE THREAD

**Issue by esl4m** [Knawat/knawat-dropshipping-magento2#52]
Errors during compilation. 

Issue:
"We can't add this item to your shopping cart right now." 
message appears when try to add a product to Cart

Note: this issue exists only after the extension was installed and you don't change extension configuration. 
If configure extension (even with invalid credentials) issue will not appear again.

**Comment by HazemKhaled** [comment]
Since Magento decided to remove 2.1 support from Marketplace on July 11th, 2019, so no need to keep working on it
