### ISSUE TITLE
No Image to configurable products 

### ISSUE THREAD

**Issue by melobat** [Knawat/knawat-dropshipping-magento2#53]
I downloaded and installed knawat extension v 1.0.5 for magento v 2.3.1
I can import all information about products that i am selecting from knawat website into my store's admin panel except the images, so i can't see any image for my products in admin panel and in my frontend of my store. Is there any problem with that point?

**Comment by HazemKhaled** [comment]
@melobat fixed in last version 1.0.6, check installation guide to get last version https://github.com/Knawat/knawat-dropshipping-magento2/wiki/1.-Installation-Guide

close the issue if it fixed

**Comment by melobat** [comment]
After the upgrade you made yesterday to version 1.0.6 the problem is solved

**Comment by melobat** [comment]
It is an important fix thank you.
