### ISSUE TITLE
Class Knawat\MPFactory does not exist

### ISSUE THREAD

**Issue by sfbarboza** [Knawat/knawat-dropshipping-magento2#65]
hi, i have the following problem installing magento 2.3.3  "Class Knawat \ MPFactory does not exist"

Tanks

**Comment by hamusthekiller** [comment]
Hello @sfbarboza,
You should install KnawatSDK for Magento2 in your composer file and error will be fixed.

**Comment by asamaaa** [comment]
how to install KnawatSDK for Magento2

**Comment by asamaaa** [comment]
[ervanama@de6 code]$ composer require knawat/knawat-php-sdk
No composer.json in current directory, do you want to use the one at /home/ervanama/public_html/magento2? [Y,n]? y
Using version ^1.0 for knawat/knawat-php-sdk
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)


Fatal error: Allowed memory size of 1610612736 bytes exhausted (tried to allocate 67108864 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Solver.php on line 223

Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.[ervanama@de6 code]$
[ervanama@de6 code]$ composer require knawat/knawat-php-sdk
No composer.json in current directory, do you want to use the one at /home/ervanama/public_html/magento2? [Y,n]? y
Using version ^1.0 for knawat/knawat-php-sdk
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)

**Comment by asamaaa** [comment]
plss help

**Comment by hamusthekiller** [comment]
Hello @asamaaa,
You need to include Knawat SDK for Magento 2 in your composer.json file in your Magento 2 directory to be able to install and run it normally. The problem U have here besides Knawat SDK is a memory issue, for Magento 2 to run smoothly You need at least 2 GB of RAM.
If You need any other help there is a chat for developers in https://gitter.im/Knawat/Lobby
or You can open a support ticket at support@knawat.com
This issue will be closed as it isn't its place to post it.
Have a great day.
