### ISSUE TITLE
Unable to connect Knawat

### ISSUE THREAD

**Issue by HeshamIsmail** [Knawat/knawat-dropshipping-magento2#84]
**Describe the bug**

After saving Knawat consumer and secret key, the user gets a system message:

"Your store is not connected to Knawat, Please Enter valid consumer key and secret key from Settings." and the user becomes unable to import any products.
 
**To Reproduce**

Steps to reproduce the behavior.
1. Go to Magento2 admin store.
2. Click on Dropshing ->Settings.
3. Add Consumer and secret key then save
4. Go Dropshing ->Product import.

Result: system message: "Your store is not connected to Knawat, Please Enter valid consumer key and secret key from Settings." and the user becomes unable to import any products.

Expected result: Store stays connected to Knawat and user gets the ability to import products normally.

**Screenshots**
1-Screenshot for the system message.

![image](https://user-images.githubusercontent.com/74185849/106761350-c6dbc400-6645-11eb-9245-5735b92bd712.png)

**Enviroment (please complete the following information):**
 - OS: **Windows**
 - Browser [e.g. chrome, safari]: **Chrome**
 - Plugin Version: ----
 - Magento Version [e.g. 22]:**2.2.6**

**Additional context**

**Comment by HeshamIsmail** [comment]
Kindly check @iamdharmesh

**Comment by HeshamIsmail** [comment]
@iamdharmesh @HazemKhaled 
The connection issue is fixed after the PHP-SDK recent fix but we are still unable to import products.

**Comment by jayjittv** [comment]
I have received  the details and checking the issue

**Comment by tatva-wct** [comment]
@HeshamIsmail as we already added backward compatibility at MP and fixed PHP-SDK also. So, this issue fixed now can you please help to close it.

**Comment by iamdharmesh** [comment]
@HeshamIsmail as we already added backward compatibility at MP and fixed PHP-SDK. can you please help to close this issue. Thanks

**Comment by HeshamIsmail** [comment]
Fixed from PHP-SDK
