### ISSUE TITLE
Unable to import products

### ISSUE THREAD

**Issue by HeshamIsmail** [Knawat/knawat-dropshipping-magento2#85]
The connection issue is fixed after the PHP-SDK recent fix but we are still unable to import products.

**Steps to replicate:**

1-Go to Magento2 admin store.
2-Click on Dropshing ->Settings.
3-Add Consumer and secret key then save
4-Go Dropshing ->Product import.

Result: The page is blank and the user becomes unable to import any products.

Expected result: Store gets the ability to import products normally.

**Troubleshooting steps:**

1-User reinstalled and reconfigured Knawat extension on Magento2 but still unable to import products.

**Attachments:**

1-Screenshot showing the import page

image
![image](https://user-images.githubusercontent.com/74185849/107356036-54edf980-6ae1-11eb-84c2-fccc2aaac7ed.png)

image
![image](https://user-images.githubusercontent.com/74185849/107356068-63d4ac00-6ae1-11eb-81e1-76988fd16a62.png)

**Comment by HeshamIsmail** [comment]
@iamdharmesh please check it

**Comment by jayjittv** [comment]
@HeshamIsmail 
Can you please let me know , in which magento version we are facing this or is it related to any specific customer's issue ?

**Comment by HeshamIsmail** [comment]
Hello Jayjit Magento version 2.2.6.

![image](https://user-images.githubusercontent.com/74185849/107369362-bff3fc00-6af2-11eb-9a93-796c78f88072.png)

**Comment by jayjittv** [comment]
@iamdharmesh @HeshamIsmail 
It was customer specific issue and its fixed and working now . Please check and let me know if you have any concern/query for this

**Comment by HeshamIsmail** [comment]
The issue was resolved
